// <auto-generated />
using System;
using CAPA_DATOS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CAPA_DATOS.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CAPA_NEGOCIO.ENTIDADES.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentarios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("CAPA_NEGOCIO.ENTIDADES.ComentarioPublicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ComentarioNavigatorId")
                        .HasColumnType("int");

                    b.Property<int>("ComentariosID")
                        .HasColumnType("int");

                    b.Property<int>("PublicacionID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComentarioNavigatorId");

                    b.HasIndex("PublicacionID");

                    b.ToTable("ComentarioPublicacion");
                });

            modelBuilder.Entity("CAPA_NEGOCIO.ENTIDADES.Publicacion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("CAPA_NEGOCIO.ENTIDADES.ComentarioPublicacion", b =>
                {
                    b.HasOne("CAPA_NEGOCIO.ENTIDADES.Comentario", "ComentarioNavigator")
                        .WithMany()
                        .HasForeignKey("ComentarioNavigatorId");

                    b.HasOne("CAPA_NEGOCIO.ENTIDADES.Publicacion", "PublicacionNavigator")
                        .WithMany()
                        .HasForeignKey("PublicacionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
